import { Inter } from "next/font/google";
import "./globals.css";

import Googleadsec from "./Gogeladasence"
import Header from "../components/Header"
import Footer from "../components/Footer"
const inter = Inter({ subsets: ["latin"] });
import styles from "./page.module.css";
import { Analytics } from '@vercel/analytics/react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Googleadsec />
      <body className={inter.className}>


        <Header />
        {children}
        <Analytics />

        <Footer />
      </body>
    </html>

  );
}
